services:
  app:
    container_name: download-center
    image: xinboo/download-center
    build: .
    ports:
      - "8081:8080"
    volumes:
      - ./appsettings.json:/app/appsettings.json
      - ./uploads:/app/uploads
      - ./favicon.ico:/app/wwwroot/favicon.ico
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
